Connected successfully
It's connected, we can rock the data!
Iteracja nr:  0
Traceback (most recent call last):
  File "connect.py", line 7, in <module>
    chamber1.update()
  File "/home/debian/projects/chamber/chamberClass.py", line 63, in update
    self.tempTab.append(self.tempData())
  File "/home/debian/projects/chamber/chamberClass.py", line 103, in tempData
    PV, SP, lowVal, maxVal = changeAnsForTable(sendAndReceive(self.ser, self.tempAsk))
  File "/home/debian/projects/chamber/functions.py", line 56, in changeAnsForTable
    PV = retFloatFromString(tempStr)
  File "/home/debian/projects/chamber/functions.py", line 37, in retFloatFromString
    retFloat = float(int(newFirstStr)) + (float(int(newLastStr)) / pow(10, (len(newLastStr))))
ValueError: invalid literal for int() with base 10: ''
Exception ignored in: <bound method Chamber.__del__ of <chamberClass.Chamber object at 0xb6ad4d70>>
Traceback (most recent call last):
  File "/home/debian/projects/chamber/chamberClass.py", line 50, in __del__
  File "/home/debian/projects/chamber/functions.py", line 74, in saveToFile
  File "/usr/lib/python3.5/encodings/__init__.py", line 98, in search_function
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
